services:
  web:
    build: 
      context: ./project
      dockerfile: Dockerfile.fastapi
    container_name: fastapi
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./project:/app
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq=service
    ports:
      - "5672:5672"
      - "15672:15672"
  
  worker:
    build: 
      context: ./project
      dockerfile: Dockerfile.celery
    container_name: celery
    command: celery -A worker.celery_app worker --loglevel=info
    volumes:
      - ./project:/app
    depends_on:
      - rabbitmq
      - web

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
    depends_on:
      - web
      - worker
      - rabbitmq

  prometheus:
    image: prom/prometheus
    volumes:
      - ./project/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - pushgateway

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  
