# Dockerfile.celery
FROM python:3.9-slim

WORKDIR /app

COPY ./project/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./project /app

CMD ["celery", "-A", "worker", "worker", "--loglevel=info"]

