apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway  
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
      - name: pushgateway
        image: prom/pushgateway
        ports:
        - containerPort: 9091

---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway-service
spec:
  selector:
    app: pushgateway
  ports:
  - protocol: TCP
    port: 9091
    targetPort: 9091
    name: metrics
    type: LoadBalancer
  
